# Bem vindo ao Jekyll!
#
# Este arquvivo de configuração é para definições que afetam todo o seu blog,
# valores que você deve configurar uma vez e depois raramente precisará editar algo aqui.
# Por motivos técnicos este arquivo não é recarregado automáticamente quando você usa o comando
# 'jekyll serve'. Se você alterar esse arquivo, reinicie o processo no servidor.

# Configurações do Site
title: Portal Jekyll
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Configurações de Markdown 
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Configurações de Sass
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Configurações de Build
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - CNAME
  - node_modules
  - assets/sass

# Plugins
gems:
  - jekyll-feed
  - jekyll-sitemap
